### ISSUE TITLE
Does Not Run with Bun

### ISSUE THREAD

**Issue by Barzi-Ahmed** [eslint/config-inspector#102]
Hi, 

I use Bun for my project, and when I try to use "bun x eslint --inspect-config" or "bun x --bun eslint --inspect-config", it doesn't work and shows this error message:

```
$ eslint --inspect-config
You can also run this command directly using 'npx @eslint/config-inspector@latest' in the same directory as your configuration file.
'npx' is not recognized as an internal or external command,
operable program or batch file.
```

Please support Bun.

**Comment by voxpelli** [comment]
All the info you need is there in the message that’s printed?

As it say: `eslint --inspect-config` is simply a shortcut within `eslint` that runs `npx @eslint/config-inspector`

Since you’re on Bun the `npx` command fails. Do what the command recommends and do the Bun equivalent of `npx @eslint/config-inspector` directly instead of using the shortcut.

If you do want to file an issue about adding support for Bun in the shortcut, then you would have to file it towards the main ESLint project, not the config inspector.

**Comment by Razunter** [comment]
I get this error with all package managers in my project managed with bun

**Comment by Razunter** [comment]
@antfu but it's not the Bun bug. I'm getting the same issue without Bun on Node v23

**Comment by voxpelli** [comment]
@Razunter @antfu Node 23, 22, 20 should all be tested in the CI but currently only latest LTS is. I suggest a PR to add the other versions to the text matrix
