### ISSUE TITLE
Cannot find Eslint config file

### ISSUE THREAD

**Issue by carlosriveroib** [eslint/config-inspector#82]
Hi, when I try to use it I got this message

<img width="1241" alt="Captura de pantalla 2024-08-15 a las 10 09 59" src="https://github.com/user-attachments/assets/05ce6a6f-fc12-439f-a079-c5030916d603">

I have an .eslintrc.js file at the root the project. Also tried renaming it to .eslint.config.js having the same issue

This is my eslint config

<img width="502" alt="Captura de pantalla 2024-08-15 a las 10 10 41" src="https://github.com/user-attachments/assets/39925a46-6f65-4182-9db0-049e6c90e9d9">

Thank you

**Comment by voxpelli** [comment]
That config is not the new flat config style, this inspector only supports inspecting flat configs (eg. `eslint.config.js`)

See migration docs for how you can migrate: https://eslint.org/docs/latest/use/configure/migration-guide

---

I think this issue is good to keep open though, as the error message could be improved – both to detect the presence of a legacy config and warn explicitly about that, and else to tell where it looked for the file, so that its easier to debug.

Also: The stack trace is unnecessary for this kind of error.

**Comment by voxpelli** [comment]
@carlosriveroib The new version should give you a better error message and as such help you figure this out 🙏
